//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cliente.ServiceReference2 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.ServicioSoap")]
    public interface ServicioSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarLocalidades", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ListarLocalidades();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarLocalidades", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ListarLocalidadesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarxLocalidad", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ListarxLocalidad(string localidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListarxLocalidad", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ListarxLocalidadAsync(string localidad);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicioSoapChannel : Cliente.ServiceReference2.ServicioSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioSoapClient : System.ServiceModel.ClientBase<Cliente.ServiceReference2.ServicioSoap>, Cliente.ServiceReference2.ServicioSoap {
        
        public ServicioSoapClient() {
        }
        
        public ServicioSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet ListarLocalidades() {
            return base.Channel.ListarLocalidades();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ListarLocalidadesAsync() {
            return base.Channel.ListarLocalidadesAsync();
        }
        
        public System.Data.DataSet ListarxLocalidad(string localidad) {
            return base.Channel.ListarxLocalidad(localidad);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ListarxLocalidadAsync(string localidad) {
            return base.Channel.ListarxLocalidadAsync(localidad);
        }
    }
}
